In [1]:
# Import packages

import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim

from One_Hot import *

In [2]:
bruh = One_Hot("Base Pair", 'ACGT')

print(bruh)

print(np.shape(bruh))

[0. 0. 0. 0.]
[1. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 1.]
[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
(16,)


In [ ]:
import torch
torch.cuda.is_available()

In [ ]:
# Define network architecture
class MyModel(nn.Module):
  def __init__(self):
    super(MyModel, self).__init__()
    self.dense1 = nn.Linear(2, 64)
    self.relu1 = nn.ReLU()
    self.dense2 = nn.Linear(64, 3)

  # Forward pass
  def forward(self, x):
    x = self.dense1(x)
    x = self.relu1(x)
    x = self.dense2(x)
    return x


In [ ]:
# Define the model
model = MyModel()

# Loss and optimizer
loss_function = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.05, weight_decay=5e-7)

In [ ]:
# Define training data and labels (X, y)

In [ ]:
# Train in loop
for epoch in range(10001):
    # Forward pass
    outputs = model(X)

    # Calculate the loss
    loss = loss_function(outputs, y)

    # Zero gradients, backward pass, and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Calculate accuracy
    _, predicted = torch.max(outputs, 1)
    accuracy = (predicted == y).float().mean()

    # Print epoch, accuracy, loss, learning rate every 100 epochs
    if epoch % 100 == 0:
        print(f'Epoch: {epoch}, Accuracy: {accuracy.item():.3f}, Loss: {loss.item():.3f}, Learning Rate: {optimizer.param_groups[0]["lr"]}')
